language: android

android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.2
  - android-23

sudo: false

script: "./gradlew build signing --stacktrace"

deploy:
  provider: releases
  api_key:
    secure: VrJUjO5FmldnmyIMeWXNgQblBDu8FkrDWqo/0kJFpQvSqfSOxRiz4+wMUsbSp7SEsvdHQoQiVxctK5X9tdf7Z0PWidFV4BFud5oM64SiDklDOKRJADKiF3+axmrnk6BCcoF4AZugvW0/ShxSFJaahfQHKnTwnC2AmbV7b0HfYQA=
  file_glob: true
  file: "**/*-release.apk"
  on:
    tags: true
