language: android

sudo: false
dist: trusty

jdk: oraclejdk8

android:
  components:
  - tools
  - build-tools-26.0.1
  - android-26

addons:
  apt:
    packages:
      - ruby

install:
  - rvm default exec gem install fastlane
  - which fastlane
  - echo $PATH

script:
  - ./gradlew build

deploy:
  - provider: script
    skip_cleanup: true
    script: find . -name '*.apk'
  - provider: script
  skip_cleanup: true
    script: ./test_fastlane.sh